### ISSUE TITLE
Update reusable NTAC XML artifacts to UTF-8

### ISSUE THREAD

**Issue by webb** [NIEM/NTAC#17]
From 2020-07-07 NTAC TSWG meeting
Establish that reusable XML artifacts should be encoded as UTF-8, to ensure maximum reusability, barring other specific requirements.

- [ ] Add as a note in the wiki for repo NIEM/NTAC
- [x] Update XML artifacts in NTAC specifications to UTF-8

**Comment by douklias** [comment]
Update to UTF-8 is needed to be more universal.
