### ISSUE TITLE
Name of Conformance Targets Attribute

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NTAC#36]
Would the concept be easier for users to understand if it was called something like `artifact` or `ruleSet`?  Conformance targets and conformance target identifiers have not been intuitively understood terms.

Dr. Scott: Change to `conformsTo`
Jim Cabral: Change to `conformanceClaim`

#resolved Change to something, don't know what

**Comment by cdmgtri** [comment]
NTAC has decided renaming the attribute isn't worth the impact to the schemas and specifications.  No change.
