### ISSUE TITLE
XML Schema 1.1

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NTAC#46]
Explore the use of XML Schema 1.1 for NIEM 6.0?

[What's New in XML Schema 1.1?](https://www.altova.com/blog/what-s-new-in-xml-schema-11/)

If we add new schema features to the NIEM XML profile, maybe we do so only if there is a way to translate back to XSD 1.0.  Similar to supporting NIEM XML and NIEM JSON formats.  We have a NIEM XML (XSD 1.0) and a NIEM XML (XSD 1.1) format.  Just another XSD 1.0 module that could be plugged into the metamodel architecture.

**Comment by cdmgtri** [comment]
The NTAC has determined that there is not enough tool support for XML Schema 1.1 at this time.
