### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NTAC#48]
- Let users build assertions right into their subsets and extension schemas.
- Would XSD 1.1 be easier for most people than evaluating Schematron rules in a separate step?
- More of a standard way of defining and evaluating business rules on the XML side for NIEM rather than just directing users to Schematron or to write a custom solution in their application?
- Users can currently add cardinality constraints in subsets; also give them some standard options for additional business rules that our tools could generate for them?  (Easier for most users without Schematron background.)
- If we support known kinds of business rules, we could come up with a way to represent them in NIEM JSON as well.
- Can represent separately via Schematron with XSD 1.0.

Looks like assertions are type-based; Schematron still useful for property-based assertions.

**Comment by cdmgtri** [comment]
The NTAC has determined that there is not enough tool support for XML Schema 1.1 at this time.
