### ISSUE TITLE
Schema-Wide Attributes

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NTAC#49]
"XML Schema 1.1 allows you to define a set of default attributes that automatically apply to every complex type in the schema... The `xs:schema` element in XML Schema 1.1 has an optional `defaultAttributes` element, which identifies an attribute group."

[What's New in XML Schema 1.1?](https://www.altova.com/blog/what-s-new-in-xml-schema-11/)

- Would this help us propagate the `structures` attribute group to CSC types?
- Would this allow us to extend a CSC-defined code set with additional code values?

**Comment by cdmgtri** [comment]
The NTAC has determined that there is not enough tool support for XML Schema 1.1 at this time.
