### ISSUE TITLE
Minimize Attributes

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NTAC#56]
Change all the attributes containing semantic data into elements, leaving just the infrastructure support stuff.

- Makes the RDF cleaner.
- More consistent.
- Removes arguments for others to use attributes.

Christina: Some attributes, like text string stuff. Would require text elements to have a inner element.

Dr. Scott: Choices

- kill the concepts
- do as metadata
- don't do this

#todo Dr. Scott, Christina, Tom Carlson work out choices and options

**Comment by cdmgtri** [comment]
Issue migrated to niemopen/ntac-admin#24.
