### ISSUE TITLE
Combining JSON Schemas

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NTAC#60]
Can we combine JSON schemas? Dr. Scott couldn't, but Christina has had success.

Christina: Need to add the extra stuff like `choice` to the metamodel to support community content.

Dr. Scott: Is there more than just like a sub group?

Christina, Jim Cabral, Mike Hulme all say yes.

Christina: Can add keywords to JSON Schema.

**Comment by cdmgtri** [comment]
[json-schema-deref](https://github.com/cvent/json-schema-deref) is a Javascript package that will do this for you.  It will dereference JSON Schema refs within the file, to other local files, and to web resources.
